spring:
   datasource:
      url: jdbc:mysql://localhost/ecom
      username: root
      password: root
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/