spring:
   data:
      mongodb:
         uri: mongodb://localhost:27017/ecom
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
ecom:
   amqp:
      rabbit:
         address: localhost:5672
         username: guest
         password: guest
         vhost: /
         exchange: Ecom-exchange
         queue: Ecom-product-queue
  product.img.location: D:/work/study/workspace/microservices.patterns/owen_chapter17/chapter17-01/Ax2-Ecom-No-Security/productImg/
